FROM php:8.2-apache-buster
MAINTAINER Latheesan Kanesamoorthy <latheesan87@gmail.com>

# Update base system
ARG DEBIAN_FRONTEND=noninteractive
RUN apt-get update && \
    apt-get install --no-install-recommends -y wget curl nano sudo libpng-dev libzip-dev zip unzip libicu-dev

# Install & enable required php libraries
RUN pecl install -o -f redis \
    && rm -rf /tmp/pear \
    && docker-php-ext-enable redis \
    && docker-php-ext-install -j$(nproc) pcntl zip mysqli pdo_mysql gd bcmath intl

# Install Nodejs 18
RUN curl -sL https://deb.nodesource.com/setup_18.x  | bash -
RUN apt-get -y install nodejs

# Configure php & apache
RUN cp /usr/local/etc/php/php.ini-production php.ini && \
    rm -rf /etc/apache2/sites-available/* && \
    rm -rf /etc/apache2/sites-enabled/* && \
    echo 'ServerName cardanomercury.app' >> /etc/apache2/apache2.conf
COPY /docker/php.ini /usr/local/etc/php/conf.d/custom.ini
COPY /docker/cardanomercury.app.conf /etc/apache2/sites-available/cardanomercury.app.conf
RUN a2enmod rewrite && \
    a2ensite cardanomercury.app

# Clean-up
RUN sudo apt-get -y purge && sudo apt-get -y clean && \
    sudo apt-get -y autoremove && sudo rm -rf /var/lib/apt/lists/* && \
    sudo rm -rf /usr/bin/apt*

# Create cardanomercury user
RUN adduser --disabled-password --gecos '' cardanomercury && \
    echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers && \
    adduser cardanomercury sudo && \
    chown -R cardanomercury:cardanomercury /home/cardanomercury/.*

# Install composer globally
RUN php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" \
    && php composer-setup.php \
    && rm -f composer-setup.php \
    && mv composer.phar /usr/local/bin/composer

# Set cardanomercury user
USER cardanomercury
WORKDIR /home/cardanomercury/application

# Expose ports
EXPOSE 80
EXPOSE 8101
